/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ConsultaController;
import controller.MedicoController;
import controller.PacienteController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConsultaMedica;
import model.Medico;
import model.Paciente;

public class consulta_view extends javax.swing.JFrame {

    /**
     * Creates new form consulta_view
     */
    public consulta_view() {
        initComponents();
        
          // Preencher JComboBox com IDs de médicos e pacientes
        box_consulta_medico.removeAllItems();
        for (Medico m : new MedicoController().listarMedicos()) {
            box_consulta_medico.addItem(m.getId().toString());
        }

        box_consulta_paciente.removeAllItems();
        for (Paciente p : new PacienteController().listarPacientes()) {
            box_consulta_paciente.addItem(p.getId().toString());
        }

        // Atualizar tabela ao abrir
        atualizarTabela();
    }
    
     private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaConsultas.getModel();
        model.setRowCount(0);

        for (ConsultaMedica c : new ConsultaController().listarConsultas()) {
            model.addRow(new Object[]{
                c.getId(),
                c.getIdPaciente(),
                c.getIdMedico(),
                c.getExame(),
                c.getDiagnosticoCodigo(),
                c.getPrescricao(),
                c.isIndicacaoCirurgica()
            });
        }
    }

    private void limparCampos() {
        id_consulta.setText("");
        box_consulta_medico.setSelectedIndex(0);
        box_consulta_paciente.setSelectedIndex(0);
        exame.setText("");
        diagnostico.setText("");
        preescricao.setText("");
        checkbox_cirurgiaosimnao.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScroll_medico = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        imagem = new javax.swing.JLabel();
        corpo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_consulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        box_consulta_medico = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        exame = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        preescricao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        diagnostico = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        botao_limpar = new javax.swing.JToggleButton();
        botao_add = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        botao_editar = new javax.swing.JToggleButton();
        botao_remover = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        botao_excel = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaConsultas = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        checkbox_cirurgiaosimnao = new javax.swing.JCheckBox();
        botao_home = new javax.swing.JToggleButton();
        box_consulta_paciente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScroll_medico.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScroll_medico.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        imagem.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        imagem.setForeground(new java.awt.Color(255, 255, 255));
        imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\livia\\Downloads\\imagem_2025-04-15_211756036 (1).png")); // NOI18N

        corpo.setForeground(new java.awt.Color(0, 51, 102));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("CONSULTAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("*ID:");

        id_consulta.setToolTipText("");
        id_consulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_consulta.setEnabled(false);
        id_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_consultaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("*Paciente:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("DADOS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("*Médico:");

        box_consulta_medico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_consulta_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_consulta_medicoActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("*Exame (queixa):");

        exame.setToolTipText("");
        exame.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("*Diagnóstico:");

        preescricao.setToolTipText("");
        preescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        preescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preescricaoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("*Prescrição:");

        diagnostico.setToolTipText("");
        diagnostico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("DADOS HOSPITALARES:");

        botao_limpar.setBackground(new java.awt.Color(0, 51, 102));
        botao_limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_limpar.setForeground(new java.awt.Color(255, 255, 255));
        botao_limpar.setText("LIMPAR");
        botao_limpar.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_limparActionPerformed(evt);
            }
        });

        botao_add.setBackground(new java.awt.Color(0, 51, 102));
        botao_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_add.setForeground(new java.awt.Color(255, 255, 255));
        botao_add.setText("ADICIONAR");
        botao_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_addActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        botao_editar.setBackground(new java.awt.Color(0, 51, 102));
        botao_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_editar.setForeground(new java.awt.Color(255, 255, 255));
        botao_editar.setText("EDITAR");
        botao_editar.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_editarActionPerformed(evt);
            }
        });

        botao_remover.setBackground(new java.awt.Color(0, 51, 102));
        botao_remover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_remover.setForeground(new java.awt.Color(255, 255, 255));
        botao_remover.setText("REMOVER");
        botao_remover.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_removerActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("CADASTRAR CONSULTA");

        botao_excel.setBackground(new java.awt.Color(0, 51, 102));
        botao_excel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_excel.setForeground(new java.awt.Color(255, 255, 255));
        botao_excel.setText("EXCEL");
        botao_excel.setActionCommand("");
        botao_excel.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excelActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(0, 51, 102));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null)));
        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ID PACIENTE", "ID MEDICO", "EXAME", "DIAGNÓSTICOS", "PRESCRIÇÃO", "CIRURGIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaConsultas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(tabelaConsultas);
        if (tabelaConsultas.getColumnModel().getColumnCount() > 0) {
            tabelaConsultas.getColumnModel().getColumn(0).setMinWidth(120);
            tabelaConsultas.getColumnModel().getColumn(0).setPreferredWidth(120);
            tabelaConsultas.getColumnModel().getColumn(1).setMinWidth(120);
            tabelaConsultas.getColumnModel().getColumn(1).setPreferredWidth(120);
            tabelaConsultas.getColumnModel().getColumn(2).setMinWidth(120);
            tabelaConsultas.getColumnModel().getColumn(2).setPreferredWidth(120);
            tabelaConsultas.getColumnModel().getColumn(3).setMinWidth(220);
            tabelaConsultas.getColumnModel().getColumn(3).setPreferredWidth(220);
            tabelaConsultas.getColumnModel().getColumn(4).setMinWidth(250);
            tabelaConsultas.getColumnModel().getColumn(4).setPreferredWidth(250);
            tabelaConsultas.getColumnModel().getColumn(5).setMinWidth(250);
            tabelaConsultas.getColumnModel().getColumn(5).setPreferredWidth(250);
            tabelaConsultas.getColumnModel().getColumn(6).setMinWidth(120);
            tabelaConsultas.getColumnModel().getColumn(6).setPreferredWidth(120);
        }

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("*Indicação cirúrgica:");

        checkbox_cirurgiaosimnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_cirurgiaosimnaoActionPerformed(evt);
            }
        });

        botao_home.setBackground(new java.awt.Color(0, 51, 102));
        botao_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_home.setForeground(new java.awt.Color(255, 255, 255));
        botao_home.setText("HOME");
        botao_home.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_homeActionPerformed(evt);
            }
        });

        box_consulta_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_consulta_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_consulta_pacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corpoLayout = new javax.swing.GroupLayout(corpo);
        corpo.setLayout(corpoLayout);
        corpoLayout.setHorizontalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(botao_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_excel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(347, 347, 347))))
            .addGroup(corpoLayout.createSequentialGroup()
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_consulta_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_consulta_paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(corpoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, 0)
                        .addComponent(checkbox_cirurgiaosimnao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exame, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diagnostico))
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botao_add, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );
        corpoLayout.setVerticalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpoLayout.createSequentialGroup()
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(id_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(box_consulta_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(box_consulta_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(exame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(diagnostico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(preescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(checkbox_cirurgiaosimnao))
                .addGap(16, 16, 16)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jScroll_medico.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScroll_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScroll_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_consultaActionPerformed

    private void box_consulta_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_consulta_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_consulta_medicoActionPerformed

    private void exameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exameActionPerformed

    private void preescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preescricaoActionPerformed

    private void diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagnosticoActionPerformed

    private void botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_limparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_limparActionPerformed

    private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_addActionPerformed
        // TODO add your handling code here:
       try {
            Long id = id_consulta.getText().isEmpty() ? null : Long.parseLong(id_consulta.getText());
            Long idPaciente = Long.parseLong(box_consulta_paciente.getSelectedItem().toString());
            Long idMedico = Long.parseLong(box_consulta_medico.getSelectedItem().toString());
            String exameTexto = exame.getText();
            String codDiagnostico = diagnostico.getText();
            String prescricaoTexto = preescricao.getText();
            boolean cirurgia = checkbox_cirurgiaosimnao.isSelected();

            ConsultaMedica consulta = new ConsultaMedica(
                id, idPaciente, idMedico, exameTexto, codDiagnostico, prescricaoTexto, cirurgia
            );

            new ConsultaController().adicionarConsulta(consulta);

            JOptionPane.showMessageDialog(this, "Consulta cadastrada com sucesso!");
            limparCampos();
            atualizarTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar consulta: " + e.getMessage());
        }
    }//GEN-LAST:event_botao_addActionPerformed

    private void botao_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_editarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaConsultas.getSelectedRow();
        if (linhaSelecionada >= 0) {
            try {
                // Preenche os campos com os dados da linha selecionada
                id_consulta.setText(tabelaConsultas.getValueAt(linhaSelecionada, 0).toString());
                box_consulta_paciente.setSelectedItem(tabelaConsultas.getValueAt(linhaSelecionada, 1).toString());
                box_consulta_medico.setSelectedItem(tabelaConsultas.getValueAt(linhaSelecionada, 2).toString());
                exame.setText(tabelaConsultas.getValueAt(linhaSelecionada, 3).toString());
                diagnostico.setText(tabelaConsultas.getValueAt(linhaSelecionada, 4).toString());
                preescricao.setText(tabelaConsultas.getValueAt(linhaSelecionada, 5).toString());
                checkbox_cirurgiaosimnao.setSelected((boolean) tabelaConsultas.getValueAt(linhaSelecionada, 6));

                JOptionPane.showMessageDialog(this, "Dados carregados para edição. Faça as alterações e clique em ADICIONAR para salvar.");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados para edição: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para editar.");
        }
    }//GEN-LAST:event_botao_editarActionPerformed

    private void botao_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_removerActionPerformed
        // TODO add your handling code here:
            int linhaSelecionada = tabelaConsultas.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja realmente remover esta consulta?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    Long id = Long.parseLong(tabelaConsultas.getValueAt(linhaSelecionada, 0).toString());
                    new ConsultaController().removerConsulta(id);
                    JOptionPane.showMessageDialog(this, "Consulta removida com sucesso!");
                    limparCampos();
                    atualizarTabela();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao remover consulta: " + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma consulta na tabela para remover.");
        }
    }//GEN-LAST:event_botao_removerActionPerformed

    private void botao_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_excelActionPerformed

    private void checkbox_cirurgiaosimnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_cirurgiaosimnaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_cirurgiaosimnaoActionPerformed

    private void botao_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_homeActionPerformed
        // TODO add your handling code here:
        HomeView home = new HomeView(); // cria a nova tela
        home.setVisible(true);          // mostra a nova tela
        this.dispose();  
    }//GEN-LAST:event_botao_homeActionPerformed

    private void box_consulta_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_consulta_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_consulta_pacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulta_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulta_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulta_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulta_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulta_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botao_add;
    private javax.swing.JToggleButton botao_editar;
    private javax.swing.JToggleButton botao_excel;
    private javax.swing.JToggleButton botao_home;
    private javax.swing.JToggleButton botao_limpar;
    private javax.swing.JToggleButton botao_remover;
    private javax.swing.JComboBox<String> box_consulta_medico;
    private javax.swing.JComboBox<String> box_consulta_paciente;
    private javax.swing.JCheckBox checkbox_cirurgiaosimnao;
    private javax.swing.JPanel corpo;
    private javax.swing.JTextField diagnostico;
    private javax.swing.JTextField exame;
    private javax.swing.JTextField id_consulta;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScroll_medico;
    private javax.swing.JTextField preescricao;
    private javax.swing.JTable tabelaConsultas;
    // End of variables declaration//GEN-END:variables
}
