/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Medico;
import controller.MedicoController;
import model.Endereco;
import model.ContatoTelemail;
import model.Genero;

/**
 *
 * @author livia
 */
public class medico_view extends javax.swing.JFrame {

    private MedicoController medicoController = new MedicoController();

    /**
     * Creates new form medico_view
     */
    public medico_view() {
        initComponents();
        // Inicializar ComboBox de Gênero
        box_genero_med.removeAllItems();
        for (Genero genero : Genero.values()) {
            box_genero_med.addItem(genero.getDescricao());
         }
    
        // Atualizar tabela ao abrir a tela
        atualizarTabela();
    }
    
    private void limparCampos() {
        nome_med.setText("");
        data_med.setText("");
        box_genero_med.setSelectedIndex(0);
        tel_med.setText("");
        email_med.setText("");
        cel_med.setText("");
        rua_med.setText("");
        num_med.setText("");
        bairro_med.setText("");
        cidade_med.setText("");
        estado_med.setText("");
        cep_med.setText("");
        setor_med.setText("");
        id_med.setText("");
        ch_med.setText("");
        crm_med.setText("");
        especialidade_med.setText("");
        checkbox_cirurgiaosimnao.setSelected(false);
    }

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpa a tabela

        for (Medico medico : medicoController.listarMedicos()) {
            model.addRow(new Object[]{
                medico.getId(),
                medico.getNomeCompleto(),
                medico.getDataNascimento(),
                medico.getGenero(),
                medico.getContato().getTelefone(),
                medico.getContato().getCelular(),
                medico.getContato().getEmail(),
                medico.getEndereco().getRua(),
                medico.getEndereco().getNumero(),
                medico.getEndereco().getBairro(),
                medico.getEndereco().getCidade(),
                medico.getEndereco().getEstado(),
                medico.getEndereco().getCep(),
                medico.getSetor(),
                medico.getCargaHoraria(),
                medico.getCrm(),
                medico.getEspecialidade(),
                medico.getCirurgiao() ? "Sim" : "Não"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScroll_medico = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        imagem = new javax.swing.JLabel();
        corpo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome_med = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        data_med = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        box_genero_med = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tel_med = new javax.swing.JTextField();
        email_med = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cel_med = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rua_med = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bairro_med = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cidade_med = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        estado_med = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cep_med = new javax.swing.JTextField();
        num_med = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        setor_med = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ch_med = new javax.swing.JTextField();
        botao_limpar = new javax.swing.JToggleButton();
        botao_add = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        botao_editar = new javax.swing.JToggleButton();
        botao_remover = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        botao_excel = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        id_med = new javax.swing.JTextField();
        crm_med = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        especialidade_med = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        checkbox_cirurgiaosimnao = new javax.swing.JCheckBox();
        botao_home = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScroll_medico.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScroll_medico.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        imagem.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        imagem.setForeground(new java.awt.Color(255, 255, 255));
        imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\livia\\Downloads\\imagem_2025-04-15_211756036 (1).png")); // NOI18N

        corpo.setForeground(new java.awt.Color(0, 51, 102));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("MÉDICOS CADASTRADOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("*Nome completo:");

        nome_med.setToolTipText("");
        nome_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nome_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_medActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("*Data nascimento:");

        data_med.setToolTipText("");
        data_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        data_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data_medActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("DADOS PESSOAIS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("*Gênero:");

        box_genero_med.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box_genero_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_genero_medActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("*Telefone:");

        tel_med.setToolTipText("");
        tel_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tel_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tel_medActionPerformed(evt);
            }
        });

        email_med.setToolTipText("");
        email_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_medActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("*E-mail:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("*Celular:");

        cel_med.setToolTipText("");
        cel_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cel_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cel_medActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("DADOS HOSPITALARES:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("*Rua");

        rua_med.setToolTipText("");
        rua_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        rua_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rua_medActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("*Número:");

        bairro_med.setToolTipText("");
        bairro_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bairro_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairro_medActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("*Bairro:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("*Cidade:");

        cidade_med.setToolTipText("");
        cidade_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cidade_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidade_medActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("*Estado:");

        estado_med.setToolTipText("");
        estado_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        estado_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_medActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("*CEP:");

        cep_med.setToolTipText("");
        cep_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cep_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cep_medActionPerformed(evt);
            }
        });

        num_med.setToolTipText("");
        num_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        num_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_medActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("ENDEREÇO:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("*Setor:");

        setor_med.setToolTipText("");
        setor_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setor_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setor_medActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("*Carga horária (semanal):");

        ch_med.setToolTipText("");
        ch_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ch_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_medActionPerformed(evt);
            }
        });

        botao_limpar.setBackground(new java.awt.Color(0, 51, 102));
        botao_limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_limpar.setForeground(new java.awt.Color(255, 255, 255));
        botao_limpar.setText("LIMPAR");
        botao_limpar.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_limparActionPerformed(evt);
            }
        });

        botao_add.setBackground(new java.awt.Color(0, 51, 102));
        botao_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_add.setForeground(new java.awt.Color(255, 255, 255));
        botao_add.setText("ADICIONAR");
        botao_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_addActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        botao_editar.setBackground(new java.awt.Color(0, 51, 102));
        botao_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_editar.setForeground(new java.awt.Color(255, 255, 255));
        botao_editar.setText("EDITAR");
        botao_editar.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_editarActionPerformed(evt);
            }
        });

        botao_remover.setBackground(new java.awt.Color(0, 51, 102));
        botao_remover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_remover.setForeground(new java.awt.Color(255, 255, 255));
        botao_remover.setText("REMOVER");
        botao_remover.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_removerActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("CADASTRAR MÉDICO");

        botao_excel.setBackground(new java.awt.Color(0, 51, 102));
        botao_excel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_excel.setForeground(new java.awt.Color(255, 255, 255));
        botao_excel.setText("EXCEL");
        botao_excel.setActionCommand("");
        botao_excel.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excelActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(0, 51, 102));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(), null)));
        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "DT_NASC", "GÊNERO", "TELEFONE", "CELULAR", "EMAIL", "RUA", "NUMERO", "BAIRRO", "CIDADE", "ESTADO", "CEP", "SETOR", "CH", "CRM", "ESPECIALIDADE", "CIRURGIÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(250);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(2).setMinWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(3).setMinWidth(120);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(4).setMinWidth(150);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(5).setMinWidth(150);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(6).setMinWidth(300);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(7).setMinWidth(300);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(8).setMinWidth(120);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(9).setMinWidth(200);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(10).setMinWidth(200);
            jTable1.getColumnModel().getColumn(10).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(11).setMinWidth(200);
            jTable1.getColumnModel().getColumn(11).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(12).setMinWidth(170);
            jTable1.getColumnModel().getColumn(12).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(13).setMinWidth(170);
            jTable1.getColumnModel().getColumn(13).setPreferredWidth(170);
            jTable1.getColumnModel().getColumn(14).setMinWidth(150);
            jTable1.getColumnModel().getColumn(14).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(15).setMinWidth(150);
            jTable1.getColumnModel().getColumn(15).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(16).setMinWidth(200);
            jTable1.getColumnModel().getColumn(16).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(17).setMinWidth(150);
            jTable1.getColumnModel().getColumn(17).setPreferredWidth(150);
        }

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("*ID:");

        id_med.setToolTipText("");
        id_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_med.setEnabled(false);
        id_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_medActionPerformed(evt);
            }
        });

        crm_med.setToolTipText("");
        crm_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        crm_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crm_medActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("*CRM:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("*Especialidade:");

        especialidade_med.setToolTipText("");
        especialidade_med.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        especialidade_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidade_medActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("*Cirurgião:");

        checkbox_cirurgiaosimnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbox_cirurgiaosimnaoActionPerformed(evt);
            }
        });

        botao_home.setBackground(new java.awt.Color(0, 51, 102));
        botao_home.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botao_home.setForeground(new java.awt.Color(255, 255, 255));
        botao_home.setText("HOME");
        botao_home.setPreferredSize(new java.awt.Dimension(108, 27));
        botao_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corpoLayout = new javax.swing.GroupLayout(corpo);
        corpo.setLayout(corpoLayout);
        corpoLayout.setHorizontalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(corpoLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nome_med, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(corpoLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(box_genero_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(data_med, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(email_med))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel_med, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cel_med, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(corpoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rua_med, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(num_med, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairro_med, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, corpoLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cep_med, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, corpoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estado_med))
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cidade_med, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(corpoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setor_med, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(corpoLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(especialidade_med))
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(corpoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_med, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crm_med, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_med, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, 0)
                        .addComponent(checkbox_cirurgiaosimnao)))
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(380, 380, 380))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGap(342, 342, 342))
                        .addGroup(corpoLayout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(botao_add, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_remover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corpoLayout.createSequentialGroup()
                        .addComponent(botao_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botao_excel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(381, 381, 381))))
        );
        corpoLayout.setVerticalGroup(
            corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corpoLayout.createSequentialGroup()
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nome_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(data_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(box_genero_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel20)
                        .addGap(40, 40, 40)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tel_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cel_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(email_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cidade_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(estado_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cep_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(corpoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(rua_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(num_med))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(bairro_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(setor_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(crm_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ch_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(id_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(especialidade_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(checkbox_cirurgiaosimnao))
                .addGap(28, 28, 28)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(corpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_home, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao_excel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imagem)
                .addContainerGap(892, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(corpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jScroll_medico.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScroll_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScroll_medico, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_medActionPerformed

    private void data_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data_medActionPerformed

    private void box_genero_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_genero_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_genero_medActionPerformed

    private void tel_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tel_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tel_medActionPerformed

    private void email_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_medActionPerformed

    private void cel_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cel_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cel_medActionPerformed

    private void rua_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rua_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rua_medActionPerformed

    private void bairro_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairro_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairro_medActionPerformed

    private void cidade_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidade_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidade_medActionPerformed

    private void estado_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estado_medActionPerformed

    private void cep_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cep_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cep_medActionPerformed

    private void num_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_medActionPerformed

    private void setor_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setor_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setor_medActionPerformed

    private void ch_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_medActionPerformed

    private void botao_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_limparActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_botao_limparActionPerformed

   private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        Long id;

        if (id_med.getText().isEmpty()) {
            id = (long) (medicoController.listarMedicos().size() + 1);
        } else {
            id = Long.parseLong(id_med.getText());
        }

        id_med.setText(String.valueOf(id)); // Atualiza visualmente

        Medico medico = new Medico(
            id,
            nome_med.getText(),
            data_med.getText(),
            new Endereco(
                rua_med.getText(),
                Integer.parseInt(num_med.getText()),
                bairro_med.getText(),
                cidade_med.getText(),
                estado_med.getText(),
                cep_med.getText()
            ),
            new ContatoTelemail(
                tel_med.getText(),
                cel_med.getText(),
                email_med.getText()
            ),
            Genero.fromDescricao(box_genero_med.getSelectedItem().toString()),
            setor_med.getText(),
            Integer.parseInt(ch_med.getText()),
            Integer.parseInt(crm_med.getText()),
            especialidade_med.getText(),
            checkbox_cirurgiaosimnao.isSelected()
        );

        if (medicoController.buscarPorId(id) == null) {
            medicoController.adicionarMedico(medico);
            JOptionPane.showMessageDialog(this, "Médico cadastrado com sucesso!");
        } else {
            medicoController.atualizarMedico(medico);
            JOptionPane.showMessageDialog(this, "Médico atualizado com sucesso!");
        }

        limparCampos();
        atualizarTabela();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}


    private void botao_editarActionPerformed(java.awt.event.ActionEvent evt) {
    int linha = jTable1.getSelectedRow();
    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um médico na tabela!");
        return;
    }

    try {
        Long id = (Long) jTable1.getValueAt(linha, 0);
        Medico medico = medicoController.buscarPorId(id);

        if (medico == null) {
            JOptionPane.showMessageDialog(this, "Médico não encontrado.");
            return;
        }

        // Preencher os campos com os dados do médico
        id_med.setText(medico.getId().toString());
        nome_med.setText(medico.getNomeCompleto());
        data_med.setText(medico.getDataNascimento());
        box_genero_med.setSelectedItem(medico.getGenero().getDescricao());
        tel_med.setText(medico.getContato().getTelefone());
        cel_med.setText(medico.getContato().getCelular());
        email_med.setText(medico.getContato().getEmail());
        rua_med.setText(medico.getEndereco().getRua());
        num_med.setText(medico.getEndereco().getNumero().toString());
        bairro_med.setText(medico.getEndereco().getBairro());
        cidade_med.setText(medico.getEndereco().getCidade());
        estado_med.setText(medico.getEndereco().getEstado());
        cep_med.setText(medico.getEndereco().getCep());
        setor_med.setText(medico.getSetor());
        ch_med.setText(medico.getCargaHoraria().toString());
        crm_med.setText(medico.getCrm().toString());
        especialidade_med.setText(medico.getEspecialidade());
        checkbox_cirurgiaosimnao.setSelected(medico.getCirurgiao());

        // ATENÇÃO: não atualizar nada aqui ainda!

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
    }
}




    private void botao_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_removerActionPerformed
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow();
        if (linha == -1) return;

        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja remover este médico?", 
            "Confirmação", 
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacao == JOptionPane.YES_OPTION) {
            Long id = (Long) jTable1.getValueAt(linha, 0);
            new MedicoController().removerMedico(id);
            atualizarTabela();
    }
    }//GEN-LAST:event_botao_removerActionPerformed

    private void botao_excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botao_excelActionPerformed

    private void id_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_medActionPerformed

    private void crm_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crm_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crm_medActionPerformed

    private void especialidade_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidade_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidade_medActionPerformed

    private void checkbox_cirurgiaosimnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbox_cirurgiaosimnaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkbox_cirurgiaosimnaoActionPerformed

    private void botao_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_homeActionPerformed
        // TODO add your handling code here:
	HomeView home = new HomeView(); // cria a nova tela
        home.setVisible(true);          // mostra a nova tela
        this.dispose();                 // fecha a tela atual (medico_view)
    }//GEN-LAST:event_botao_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medico_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medico_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medico_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medico_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medico_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro_med;
    private javax.swing.JToggleButton botao_add;
    private javax.swing.JToggleButton botao_editar;
    private javax.swing.JToggleButton botao_excel;
    private javax.swing.JToggleButton botao_home;
    private javax.swing.JToggleButton botao_limpar;
    private javax.swing.JToggleButton botao_remover;
    private javax.swing.JComboBox<String> box_genero_med;
    private javax.swing.JTextField cel_med;
    private javax.swing.JTextField cep_med;
    private javax.swing.JTextField ch_med;
    private javax.swing.JCheckBox checkbox_cirurgiaosimnao;
    private javax.swing.JTextField cidade_med;
    private javax.swing.JPanel corpo;
    private javax.swing.JTextField crm_med;
    private javax.swing.JTextField data_med;
    private javax.swing.JTextField email_med;
    private javax.swing.JTextField especialidade_med;
    private javax.swing.JTextField estado_med;
    private javax.swing.JTextField id_med;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScroll_medico;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nome_med;
    private javax.swing.JTextField num_med;
    private javax.swing.JTextField rua_med;
    private javax.swing.JTextField setor_med;
    private javax.swing.JTextField tel_med;
    // End of variables declaration//GEN-END:variables
}
